<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="NMediation" Version="0.9.1" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MediationBuddy\MediationBuddy.csproj" />
  </ItemGroup>
</Project>
